### PR TITLE
Fix close hook management

### LINKED ISSUE #17: Timeout when undeploying verticle
If the Cassandra client is not closed manually, undeploy operation does not complete because the context hook does not invoke the completion handler.

### PR DESCRIPTION
**Pull request by dps123**
Fixes #17

### CODE REVIEW

**Comment by Sammers21** [comment]
@dps123, can you add a test as well?

File: src/test/java/io/vertx/cassandra/TimeoutOnVerticleUndeployTest.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+import io.vertx.ext.unit.junit.VertxUnitRunner;
+import org.junit.Test;
+import org.junit.runner.RunWith;
+
+/**
+ * This test ensures that client can be automatically closed on verticle
+ * undeploy event.
+ */
+@RunWith(VertxUnitRunner.class)
+public class TimeoutOnVerticleUndeployTest extends CassandraServiceBase {
```
Comment (tsegismont) [inline src/test/java/io/vertx/cassandra/TimeoutOnVerticleUndeployTest.java]: Can you rename this to `CloseHookTest`

File: src/test/java/io/vertx/cassandra/TimeoutOnVerticleUndeployTest.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+    public static final String TEST_CLIENT_NAME = "TEST_CLIENT";
+
+    @Test
+    public void undeployShallWorks(TestContext context) {
```
Comment (tsegismont) [inline src/test/java/io/vertx/cassandra/TimeoutOnVerticleUndeployTest.java]: Can you rename this to `testClientClosedAfterUndeploy` ?

File: src/test/java/io/vertx/cassandra/TimeoutOnVerticleUndeployTest.java [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+                    if (undeploy.succeeded()) {
+                        async.complete();
+                    } else {
+                        context.fail(undeploy.cause());
+                    }
+                });
+            } else {
+                context.fail(deploy.cause());
+            }
+        });
```
Comment (tsegismont) [inline src/test/java/io/vertx/cassandra/TimeoutOnVerticleUndeployTest.java]: Can you add a test here to make sure the client is closed. To do this, you could create a share client with `TEST_CLIENT_NAME` and verify it's connected yet (send a request and get failure).

File: src/main/java/io/vertx/cassandra/impl/CassandraClientImpl.java [hunk 4]
```diff
@@ -48,7 +48,10 @@ public CassandraClientImpl(Vertx vertx, String dataSourceName, CassandraClientOp
     cassandraHolder = lookupHolder(dataSourceName, cassandraClientOptions);
     Context ctx = Vertx.currentContext();
     if (ctx != null && ctx.owner() == vertx) {
-      ctx.addCloseHook(v -> cassandraHolder.close());
+      ctx.addCloseHook(v -> {
```
Comment (tsegismont) [inline src/main/java/io/vertx/cassandra/impl/CassandraClientImpl.java]: Can you rename `v` to `completionHandler`?

Comment (tsegismont) [reply src/main/java/io/vertx/cassandra/impl/CassandraClientImpl.java]: Also, the hook reference should be stored, so that we can remove the it when the user invokes disconnect manually.

**Comment by tsegismont** [comment]
@dps123 thanks for the test. I added a few other comments.

File: src/test/java/io/vertx/cassandra/CloseHookTest.java [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+                vertx.undeploy(deploy.result(), undeploy -> {
+                    if (undeploy.succeeded()) {
+                        async.complete();
+                    } else {
+                        context.fail(undeploy.cause());
+                    }
+                });
+            } else {
+                CassandraClient shared = CassandraClient.createShared(vertx, TEST_CLIENT_NAME);
+                context.assertTrue(!shared.isConnected());
```
Comment (tsegismont) [inline src/test/java/io/vertx/cassandra/CloseHookTest.java]: This should be tested after the verticle has been undeployed succesfully

Comment (tsegismont) [reply src/test/java/io/vertx/cassandra/CloseHookTest.java]: Thanks for the update

**Comment by tsegismont** [comment]
@dps123 have you signed the Eclipse CLA? Could you rebase your PR on master, squash commits and signoff (with `-s`) ? Thank you

**Comment by tsegismont** [comment]
@dps123 and thanks again, great job!

**Comment by dps123** [comment]
@tsegismont I signed Eclipse CLA and squash commits
