### PR TITLE
#77 - fix mac os test fail

### LINKED ISSUE #77: Tests failing on Mac
When I run the project tests I get these failures:

```
CloseHookTest.testClientClosedAfterUndeploy » AllNodesFailed Could not reach a...
  CloseHookTest.testExternalSharedClientNotClosedAfterUndeploy » AllNodesFailed ...
  SharedTest.testSharedClientNotClosed » AllNodesFailed Could not reach any cont...
  TracingTest.testBoundStatement:132->CassandraClientTestBase.initializeRandomStringKeyspace:91->CassandraClientTestBase.initializeKeyspace:101 » NoNodeAvailable
  TracingTest.testSimpleStatement » AllNodesFailed Could not reach any contact p...
  TracingTest.testSimpleStatementFailure » Timeout
```

### PR DESCRIPTION
**Pull request by Sammers21**
Auth test is being ignored on mac os because of some strange testcontainers behaviour on mac os: created auth container affects the main test container 

Fixes #77

### CODE REVIEW

File: src/test/java/io/vertx/cassandra/AuthenticationTest.java [hunk 1]
```diff
@@ -48,6 +50,12 @@
 
   private CassandraClient client;
 
+  @BeforeClass
+  public static void notMacOs(){
+    Assume.assumeFalse("Test is running on a non mac os machine",
+      System.getProperty("os.name").equals("Mac OS X"));
```
Comment (tsegismont) [inline src/test/java/io/vertx/cassandra/AuthenticationTest.java:56]:
```suggestion
    Assume.assumeFalse("Test does not work on a Mac OS", io.netty.util.internal.PlatformDependent.isOsx());
```

**Review by tsegismont — APPROVED** [review]
Thank you @Sammers21 , just a minor change requested to make sure we don't miss any case
